server:
  port: 8100



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mmall?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1120
  application:
    name: provider






mybatis:
  mapper-locations: classpath*:mappers/*.xml


logging:
  config: classpath:log/logback-spring.xml
  path: /home/n1ne/IdeaProjects/mmall/logs

password:
  salt: geelysdafaqj23ou89ZXcj@#$@#$#@KJdjklj;D../dSF.,

pagehelper:
  auto-dialect: true
  reasonable: true
  support-methods-arguments: true



devtools:
  livereload:
    enabled: true
    port: 35729
  restart:
    enabled: true

embedded:
  zookeeper:
    port: 2181


dubbo:
  scan:
    base-packages: com.n1ne.mmall.service.impl
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: zookeeper://127.0.0.1:${embedded.zookeeper.port}
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache


